### ISSUE TITLE
Allow loading plugin without IDE restart

### ISSUE THREAD

**Issue by auduchinok** [ForNeVeR/file-link-executor#10]
It'd be great to be able to use the plugin without a need to restart the whole IDE.

**Comment by ForNeVeR** [comment]
yas

**Comment by ForNeVeR** [comment]
It is possible already in the modern versions of IntelliJ-based IDEs.

All that's required to make the plugin dynamically-loadable is actually to only extend dymanic extension points. There's no special mark of anything.

Since the console filter extension point is dynamic, so the plugin is.
