### ISSUE TITLE
Add ability to open directory path in explorer 

### ISSUE THREAD

**Issue by jorgeamado** [ForNeVeR/file-link-executor#17]
It'd be nice to have the ability to open a folder path in the system explorer, ex.
`c:\please\be\so\kind\toAdd\this\feature`
`..\even\for\relative\path`
`/it/would/be/nice/to/have/it/for/unix-like/path/as/well`

I think it would be nice to open using LMB or Ctrl+LMB

**Comment by ForNeVeR** [comment]
Okay, for now, in spirit of the plugin, it will work for paths like `file:///absolute-path` or `file://../../relative-path` (relative to what? who knows!)
